name: Bug Report
description: Report a bug in LMMs-Lab Writer
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open a project with ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      placeholder: If applicable, paste screenshots or error logs.

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Web (writer.lmms-lab.com)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: e.g. 0.1.0
