name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug and how to reproduce it.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Others
    validations:
      required: true

  - type: input
    id: os_other
    attributes:
      label: If you selected "Others", please specify
      placeholder: "e.g. Linux, Ubuntu 22.04"

  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      placeholder: "App version, screenshots, logs — anything that helps."
