name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug and how to reproduce it.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Environment (optional)
      placeholder: "OS, app version, screenshots, logs — anything that helps."
