"use client";

import type { Monaco } from "@monaco-editor/react";

// Define the two editor themes: one-light (monochrome) and one-dark
export const defineEditorThemes = (monaco: Monaco) => {
  // One Light theme - clean monochrome
  monaco.editor.defineTheme("one-light", {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "0a0a0a", background: "ffffff" },
      { token: "comment", foreground: "737373", fontStyle: "italic" },
      { token: "comment.line", foreground: "737373", fontStyle: "italic" },
      { token: "comment.block", foreground: "737373", fontStyle: "italic" },
      { token: "keyword", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "keyword.control", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "keyword.operator", foreground: "0a0a0a" },
      { token: "string", foreground: "404040" },
      { token: "string.quoted", foreground: "404040" },
      { token: "string.escape", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "string.math", foreground: "404040" },
      { token: "number", foreground: "404040" },
      { token: "number.float", foreground: "404040" },
      { token: "variable", foreground: "0a0a0a" },
      { token: "variable.parameter", foreground: "404040" },
      { token: "variable.other", foreground: "0a0a0a" },
      { token: "entity.name.function", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "support.function", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "entity.name.type", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "entity.name.class", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "support.type", foreground: "0a0a0a" },
      { token: "support.class", foreground: "0a0a0a" },
      { token: "tag", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "tag.attribute.name", foreground: "404040" },
      { token: "tag.attribute.value", foreground: "404040" },
      { token: "operator", foreground: "0a0a0a" },
      { token: "delimiter", foreground: "404040" },
      { token: "delimiter.bracket", foreground: "404040" },
      { token: "constant", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "constant.language", foreground: "0a0a0a", fontStyle: "bold" },
      // LaTeX specific tokens
      { token: "keyword.latex", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "keyword.control.latex", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "support.function.latex", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "variable.parameter.latex", foreground: "404040" },
      { token: "punctuation.definition.latex", foreground: "0a0a0a" },
      { token: "markup.heading.latex", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "markup.italic.latex", foreground: "0a0a0a", fontStyle: "italic" },
      { token: "markup.bold.latex", foreground: "0a0a0a", fontStyle: "bold" },
      // Markdown
      { token: "markup.heading", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "markup.bold", foreground: "0a0a0a", fontStyle: "bold" },
      { token: "markup.italic", foreground: "0a0a0a", fontStyle: "italic" },
      { token: "markup.underline.link", foreground: "404040" },
      { token: "invalid", foreground: "0a0a0a", fontStyle: "underline" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#0a0a0a",
      "editorLineNumber.foreground": "#a3a3a3",
      "editorLineNumber.activeForeground": "#0a0a0a",
      "editorCursor.foreground": "#0a0a0a",
      "editorCursor.background": "#ffffff",
      "editor.selectionBackground": "#e5e5e5",
      "editor.selectionHighlightBackground": "#e5e5e5",
      "editor.inactiveSelectionBackground": "#f0f0f0",
      "editor.lineHighlightBackground": "#f5f5f5",
      "editor.lineHighlightBorder": "#00000000",
      "editorBracketMatch.background": "#e5e5e5",
      "editorBracketMatch.border": "#a3a3a3",
      "editorIndentGuide.background": "#e5e5e5",
      "editorIndentGuide.activeBackground": "#a3a3a3",
      "editorWhitespace.foreground": "#e5e5e5",
      "editorGutter.background": "#ffffff",
      "editorGutter.modifiedBackground": "#737373",
      "editorGutter.addedBackground": "#404040",
      "editorGutter.deletedBackground": "#0a0a0a",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#d4d4d4",
      "scrollbarSlider.hoverBackground": "#a3a3a3",
      "scrollbarSlider.activeBackground": "#737373",
      "editorWidget.background": "#fafafa",
      "editorWidget.border": "#e5e5e5",
      "editorWidget.foreground": "#0a0a0a",
      "editorSuggestWidget.background": "#fafafa",
      "editorSuggestWidget.border": "#e5e5e5",
      "editorSuggestWidget.foreground": "#0a0a0a",
      "editorSuggestWidget.selectedBackground": "#e5e5e5",
      "editorSuggestWidget.highlightForeground": "#0a0a0a",
      "editorHoverWidget.background": "#fafafa",
      "editorHoverWidget.border": "#e5e5e5",
      "editorHoverWidget.foreground": "#0a0a0a",
      "editor.findMatchBackground": "#e5e5e5",
      "editor.findMatchHighlightBackground": "#f0f0f0",
      "editor.findMatchBorder": "#a3a3a3",
      "editor.wordHighlightBackground": "#f0f0f0",
      "editor.wordHighlightStrongBackground": "#e5e5e5",
      "minimap.background": "#fafafa",
      "minimap.selectionHighlight": "#d4d4d4",
      "minimapSlider.background": "#d4d4d420",
      "minimapSlider.hoverBackground": "#d4d4d440",
      "minimapSlider.activeBackground": "#d4d4d460",
      "editorOverviewRuler.border": "#e5e5e5",
      "editorOverviewRuler.findMatchForeground": "#a3a3a3",
      "editorOverviewRuler.selectionHighlightForeground": "#a3a3a3",
      "editorError.foreground": "#0a0a0a",
      "editorWarning.foreground": "#737373",
      "editorInfo.foreground": "#a3a3a3",
      "editorBracketHighlight.foreground1": "#0a0a0a",
      "editorBracketHighlight.foreground2": "#404040",
      "editorBracketHighlight.foreground3": "#737373",
      "editorBracketHighlight.unexpectedBracket.foreground": "#0a0a0a",
    },
  });

  // One Dark theme
  monaco.editor.defineTheme("one-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "abb2bf", background: "282c34" },
      { token: "comment", foreground: "5c6370", fontStyle: "italic" },
      { token: "comment.line", foreground: "5c6370", fontStyle: "italic" },
      { token: "comment.block", foreground: "5c6370", fontStyle: "italic" },
      { token: "keyword", foreground: "c678dd" },
      { token: "keyword.control", foreground: "c678dd" },
      { token: "keyword.operator", foreground: "c678dd" },
      { token: "string", foreground: "98c379" },
      { token: "string.quoted", foreground: "98c379" },
      { token: "string.escape", foreground: "56b6c2" },
      { token: "string.math", foreground: "98c379" },
      { token: "number", foreground: "d19a66" },
      { token: "number.float", foreground: "d19a66" },
      { token: "variable", foreground: "e06c75" },
      { token: "variable.parameter", foreground: "abb2bf" },
      { token: "variable.other", foreground: "e06c75" },
      { token: "entity.name.function", foreground: "61afef" },
      { token: "support.function", foreground: "61afef" },
      { token: "entity.name.type", foreground: "e5c07b" },
      { token: "entity.name.class", foreground: "e5c07b" },
      { token: "support.type", foreground: "e5c07b" },
      { token: "support.class", foreground: "e5c07b" },
      { token: "tag", foreground: "e06c75" },
      { token: "tag.attribute.name", foreground: "d19a66" },
      { token: "tag.attribute.value", foreground: "98c379" },
      { token: "operator", foreground: "56b6c2" },
      { token: "delimiter", foreground: "abb2bf" },
      { token: "delimiter.bracket", foreground: "abb2bf" },
      { token: "constant", foreground: "d19a66" },
      { token: "constant.language", foreground: "d19a66" },
      { token: "markup.heading", foreground: "e06c75", fontStyle: "bold" },
      { token: "markup.bold", foreground: "d19a66", fontStyle: "bold" },
      { token: "markup.italic", foreground: "c678dd", fontStyle: "italic" },
      { token: "markup.underline.link", foreground: "61afef" },
      { token: "invalid", foreground: "e06c75", fontStyle: "underline" },
    ],
    colors: {
      "editor.background": "#282c34",
      "editor.foreground": "#abb2bf",
      "editorLineNumber.foreground": "#4b5263",
      "editorLineNumber.activeForeground": "#abb2bf",
      "editorCursor.foreground": "#528bff",
      "editorCursor.background": "#282c34",
      "editor.selectionBackground": "#3e4451",
      "editor.selectionHighlightBackground": "#3e445199",
      "editor.inactiveSelectionBackground": "#3e445166",
      "editor.lineHighlightBackground": "#2c313c",
      "editor.lineHighlightBorder": "#00000000",
      "editorBracketMatch.background": "#3e4451",
      "editorBracketMatch.border": "#528bff",
      "editorIndentGuide.background": "#3b4048",
      "editorIndentGuide.activeBackground": "#4b5263",
      "editorWhitespace.foreground": "#3b4048",
      "editorGutter.background": "#282c34",
      "editorGutter.modifiedBackground": "#e5c07b",
      "editorGutter.addedBackground": "#98c379",
      "editorGutter.deletedBackground": "#e06c75",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#4b526333",
      "scrollbarSlider.hoverBackground": "#4b526355",
      "scrollbarSlider.activeBackground": "#4b526377",
      "editorWidget.background": "#21252b",
      "editorWidget.border": "#3e4451",
      "editorWidget.foreground": "#abb2bf",
      "editorSuggestWidget.background": "#21252b",
      "editorSuggestWidget.border": "#3e4451",
      "editorSuggestWidget.foreground": "#abb2bf",
      "editorSuggestWidget.selectedBackground": "#3e4451",
      "editorSuggestWidget.highlightForeground": "#61afef",
      "editorHoverWidget.background": "#21252b",
      "editorHoverWidget.border": "#3e4451",
      "editorHoverWidget.foreground": "#abb2bf",
      "editor.findMatchBackground": "#42557b",
      "editor.findMatchHighlightBackground": "#314365",
      "editor.findMatchBorder": "#528bff",
      "editor.wordHighlightBackground": "#3e445166",
      "editor.wordHighlightStrongBackground": "#3e445199",
      "minimap.background": "#282c34",
      "minimap.selectionHighlight": "#3e445199",
      "minimapSlider.background": "#4b526320",
      "minimapSlider.hoverBackground": "#4b526340",
      "minimapSlider.activeBackground": "#4b526360",
      "editorOverviewRuler.border": "#3e4451",
      "editorOverviewRuler.findMatchForeground": "#528bff",
      "editorOverviewRuler.selectionHighlightForeground": "#61afef",
      "editorError.foreground": "#e06c75",
      "editorWarning.foreground": "#e5c07b",
      "editorInfo.foreground": "#61afef",
      "editorBracketHighlight.foreground1": "#61afef",
      "editorBracketHighlight.foreground2": "#c678dd",
      "editorBracketHighlight.foreground3": "#56b6c2",
      "editorBracketHighlight.unexpectedBracket.foreground": "#e06c75",
    },
  });
};
