"use client";

import type { Monaco } from "@monaco-editor/react";
import type { MonacoTheme } from "monaco-themes";
// Source: monaco-themes/themes/GitHub Light.json (v0.4.8)
import githubLightTheme from "./github-light.json";

// Supplementary editor chrome colors not included in the base GitHub Light theme
const githubLightEditorColors: Record<string, string> = {
  "editorLineNumber.activeForeground": "#24292e",
  "editorCursor.background": "#ffffff",
  "editor.selectionHighlightBackground": "#c8c8fa88",
  "editor.lineHighlightBorder": "#00000000",
  "editorBracketMatch.background": "#c8c8fa66",
  "editorBracketMatch.border": "#586069",
  "editorGutter.background": "#ffffff",
  "editorGutter.modifiedBackground": "#e36209",
  "editorGutter.addedBackground": "#22863a",
  "editorGutter.deletedBackground": "#b31d28",
  "scrollbar.shadow": "#00000000",
  "scrollbarSlider.background": "#d4d4d4",
  "scrollbarSlider.hoverBackground": "#a3a3a3",
  "scrollbarSlider.activeBackground": "#737373",
  "editorWidget.background": "#fafbfc",
  "editorWidget.border": "#e1e4e8",
  "editorWidget.foreground": "#24292e",
  "editorSuggestWidget.background": "#fafbfc",
  "editorSuggestWidget.border": "#e1e4e8",
  "editorSuggestWidget.foreground": "#24292e",
  "editorSuggestWidget.selectedBackground": "#e1e4e8",
  "editorSuggestWidget.highlightForeground": "#005cc5",
  "editorHoverWidget.background": "#fafbfc",
  "editorHoverWidget.border": "#e1e4e8",
  "editorHoverWidget.foreground": "#24292e",
  "editor.findMatchBackground": "#ffdf5d66",
  "editor.findMatchHighlightBackground": "#ffdf5d33",
  "editor.findMatchBorder": "#e36209",
  "editor.wordHighlightBackground": "#c8c8fa44",
  "editor.wordHighlightStrongBackground": "#c8c8fa66",
  "minimap.background": "#fafbfc",
  "minimap.selectionHighlight": "#c8c8fa",
  "minimapSlider.background": "#d4d4d420",
  "minimapSlider.hoverBackground": "#d4d4d440",
  "minimapSlider.activeBackground": "#d4d4d460",
  "editorOverviewRuler.border": "#e1e4e8",
  "editorOverviewRuler.findMatchForeground": "#e36209",
  "editorOverviewRuler.selectionHighlightForeground": "#005cc5",
  "editorError.foreground": "#b31d28",
  "editorWarning.foreground": "#e36209",
  "editorInfo.foreground": "#005cc5",
  "editorBracketHighlight.foreground1": "#005cc5",
  "editorBracketHighlight.foreground2": "#6f42c1",
  "editorBracketHighlight.foreground3": "#22863a",
  "editorBracketHighlight.unexpectedBracket.foreground": "#b31d28",
};

export const defineEditorThemes = (monaco: Monaco) => {
  // GitHub Light theme - imported from monaco-themes package
  const lightTheme = githubLightTheme as MonacoTheme;
  monaco.editor.defineTheme("one-light", {
    ...lightTheme,
    colors: {
      ...lightTheme.colors,
      ...githubLightEditorColors,
    },
  });

  // One Dark theme (not available in monaco-themes package)
  monaco.editor.defineTheme("one-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "abb2bf", background: "282c34" },
      { token: "comment", foreground: "5c6370", fontStyle: "italic" },
      { token: "comment.line", foreground: "5c6370", fontStyle: "italic" },
      { token: "comment.block", foreground: "5c6370", fontStyle: "italic" },
      { token: "keyword", foreground: "c678dd" },
      { token: "keyword.control", foreground: "c678dd" },
      { token: "keyword.operator", foreground: "c678dd" },
      { token: "string", foreground: "98c379" },
      { token: "string.quoted", foreground: "98c379" },
      { token: "string.escape", foreground: "56b6c2" },
      { token: "string.math", foreground: "98c379" },
      { token: "number", foreground: "d19a66" },
      { token: "number.float", foreground: "d19a66" },
      { token: "variable", foreground: "e06c75" },
      { token: "variable.parameter", foreground: "abb2bf" },
      { token: "variable.other", foreground: "e06c75" },
      { token: "entity.name.function", foreground: "61afef" },
      { token: "support.function", foreground: "61afef" },
      { token: "entity.name.type", foreground: "e5c07b" },
      { token: "entity.name.class", foreground: "e5c07b" },
      { token: "support.type", foreground: "e5c07b" },
      { token: "support.class", foreground: "e5c07b" },
      { token: "tag", foreground: "e06c75" },
      { token: "tag.attribute.name", foreground: "d19a66" },
      { token: "tag.attribute.value", foreground: "98c379" },
      { token: "operator", foreground: "56b6c2" },
      { token: "delimiter", foreground: "abb2bf" },
      { token: "delimiter.bracket", foreground: "abb2bf" },
      { token: "constant", foreground: "d19a66" },
      { token: "constant.language", foreground: "d19a66" },
      { token: "markup.heading", foreground: "e06c75", fontStyle: "bold" },
      { token: "markup.bold", foreground: "d19a66", fontStyle: "bold" },
      { token: "markup.italic", foreground: "c678dd", fontStyle: "italic" },
      { token: "markup.underline.link", foreground: "61afef" },
      { token: "invalid", foreground: "e06c75", fontStyle: "underline" },
    ],
    colors: {
      "editor.background": "#282c34",
      "editor.foreground": "#abb2bf",
      "editorLineNumber.foreground": "#4b5263",
      "editorLineNumber.activeForeground": "#abb2bf",
      "editorCursor.foreground": "#528bff",
      "editorCursor.background": "#282c34",
      "editor.selectionBackground": "#3e4451",
      "editor.selectionHighlightBackground": "#3e445199",
      "editor.inactiveSelectionBackground": "#3e445166",
      "editor.lineHighlightBackground": "#2c313c",
      "editor.lineHighlightBorder": "#00000000",
      "editorBracketMatch.background": "#3e4451",
      "editorBracketMatch.border": "#528bff",
      "editorIndentGuide.background": "#3b4048",
      "editorIndentGuide.activeBackground": "#4b5263",
      "editorWhitespace.foreground": "#3b4048",
      "editorGutter.background": "#282c34",
      "editorGutter.modifiedBackground": "#e5c07b",
      "editorGutter.addedBackground": "#98c379",
      "editorGutter.deletedBackground": "#e06c75",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#4b526333",
      "scrollbarSlider.hoverBackground": "#4b526355",
      "scrollbarSlider.activeBackground": "#4b526377",
      "editorWidget.background": "#21252b",
      "editorWidget.border": "#3e4451",
      "editorWidget.foreground": "#abb2bf",
      "editorSuggestWidget.background": "#21252b",
      "editorSuggestWidget.border": "#3e4451",
      "editorSuggestWidget.foreground": "#abb2bf",
      "editorSuggestWidget.selectedBackground": "#3e4451",
      "editorSuggestWidget.highlightForeground": "#61afef",
      "editorHoverWidget.background": "#21252b",
      "editorHoverWidget.border": "#3e4451",
      "editorHoverWidget.foreground": "#abb2bf",
      "editor.findMatchBackground": "#42557b",
      "editor.findMatchHighlightBackground": "#314365",
      "editor.findMatchBorder": "#528bff",
      "editor.wordHighlightBackground": "#3e445166",
      "editor.wordHighlightStrongBackground": "#3e445199",
      "minimap.background": "#282c34",
      "minimap.selectionHighlight": "#3e445199",
      "minimapSlider.background": "#4b526320",
      "minimapSlider.hoverBackground": "#4b526340",
      "minimapSlider.activeBackground": "#4b526360",
      "editorOverviewRuler.border": "#3e4451",
      "editorOverviewRuler.findMatchForeground": "#528bff",
      "editorOverviewRuler.selectionHighlightForeground": "#61afef",
      "editorError.foreground": "#e06c75",
      "editorWarning.foreground": "#e5c07b",
      "editorInfo.foreground": "#61afef",
      "editorBracketHighlight.foreground1": "#61afef",
      "editorBracketHighlight.foreground2": "#c678dd",
      "editorBracketHighlight.foreground3": "#56b6c2",
      "editorBracketHighlight.unexpectedBracket.foreground": "#e06c75",
    },
  });
};
