export { compile } from './commands/compile.js'
export { watch } from './commands/watch.js'
export { init } from './commands/init.js'
export { login, logout, whoami } from './commands/auth.js'
export { sync } from './commands/sync.js'
export { getConfig, setConfig } from './config.js'
